### ISSUE TITLE
CSP issues

### ISSUE THREAD

**Issue by Baroshem** [nuxt-modules/security#571]
Hello everyone, there are 2 problems with my code below. No matter what I did, I couldn't solve the problem.

Problem 1 -) When the user refreshes the page, it always redirects to the home page.

Problem 2 -) The css does not come correctly on the pages where I pull dynamic data. I added 2 images as an example. When I refresh the page the css becomes even more corrupted.

Thanks for your help.

![hatalı](https://github.com/user-attachments/assets/ecf494a1-fd79-4436-bc83-d808839cbfde)

![normal](https://github.com/user-attachments/assets/a0bceebd-9d21-4dbb-b18f-7042a29f327b)

`  security: {
    hidePoweredBy: true,
    corsHandler: {
      origin: "https://www.abc.com",
      methods: ["GET", "POST", "DELETE"],
      credentials: false
    },
    headers: {
      strictTransportSecurity: {
        maxAge: 15552000,
        includeSubdomains: true
      },
      xFrameOptions: "DENY",
      crossOriginEmbedderPolicy: "unsafe-none",
      crossOriginOpenerPolicy: "same-origin",
      crossOriginResourcePolicy: "same-origin",
      xXSSProtection: "1; mod=block",
      xPermittedCrossDomainPolicies: "none",
      contentSecurityPolicy: {
        'base-uri': ["'none'"],
        'font-src': ["'self'", 'https:', 'data:'],
        'form-action': ["'self'"],
        'img-src': ["'self'", 'https://www.facebook.com', 'https://www.google.com.tr', 'https://www.googletagmanager.com', 'https://i.ytimg.com', 'data:'],
        'frame-ancestors': ["'none'"],
        'frame-src': ["'self'", 'https://www.youtube.com/', 'https://td.doubleclick.net/'],
        'manifest-src': ["'self'"],
        'media-src': ["'self'"],
        'object-src': ["'none'"],
        "worker-src": ["'self'"],
        "script-src-attr": ["'none'"],
        'script-src': [
          "'self'",
          'https:',
          "'unsafe-inline'",
          "'nonce-{{nonce}}'"
        ],
        'style-src': ["'self'", "'unsafe-inline'"],
        "upgrade-insecure-requests": true
      },
      originAgentCluster: "?1",
      xContentTypeOptions: "nosniff",
      referrerPolicy: "strict-origin-when-cross-origin",
      xDownloadOptions: "noopen",
      xDNSPrefetchControl: "off"
    },
    allowedMethodsRestricter: {
      methods: ["GET", "POST", "DELETE"]
    },
    xssValidator: {
      methods: ["GET", "POST", "DELETE"],
      css: true,
      escapeHtml: true
    },
    requestSizeLimiter: {
      maxRequestSizeInBytes: 2000000,
      maxUploadFileRequestInBytes: 8000000
    },
    rateLimiter: {
      tokensPerInterval: 100,
      interval: 900000,
      headers: false
    },
    sri: true,
    nonce: true,
    ssg: {
      meta: true,
      hashScripts: true,
      hashStyles: false,
      exportToPresets: true
    }
  }`

_Originally posted by @bycixman35 in https://github.com/Baroshem/nuxt-security/discussions/569_

**Comment by Baroshem** [comment]
@vejja do you have a clue what could be the issue?

**Comment by vejja** [comment]
Will look at it in discussion @baroshem
