### ISSUE TITLE
RuntimeConfig explicit typing not working after adding nuxt security module

### ISSUE THREAD

**Issue by divagueame** [nuxt-modules/security#590]
### Environment

```shell
npx nuxi info
Working directory: /home/divagueame/web/nuxt/runtime                                                                                           10:49:53 PM
Nuxt project info:                                                                                                                        10:49:53 PM

------------------------------
- Operating System: Linux
- Node Version:     v20.17.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.17.1
- Nitro Version:    2.10.4
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      default
- Runtime Modules:  nuxt-security@2.1.5
- Build Modules:    -
------------------------------
```

### Nuxt Security Version

2.1.5

### Default setup used?

Yes, the bug happens even if the security option is not customized

### Security options

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2024-11-01",
  devtools: { enabled: true },

  runtimeConfig: {
    apiSecret: "", // can be overridden by NUXT_API_SECRET environment variable
    public: {
      apiBase: "", // can be overridden by NUXT_PUBLIC_API_BASE environment variable
    },
  },

  modules: ["nuxt-security"],
});
```

### Reproduction

https://github.com/divagueame/runtime-config-demo

Similar issue was discussed here.  https://github.com/nuxt-modules/security/issues/544

### Description

I want to type the runtime config like explained here:
https://nuxt.com/docs/guide/going-further/runtime-config#typing-runtime-config

On a new project, the steps explained on the docs work fine and the types in 'index.d.ts' related to PublicRuntimeConfig.
When I add nuxt security module, this types are not working anymore.

```
declare module "nuxt/schema" {
  interface RuntimeConfig {
    apiSecret: string;
  }
  interface PublicRuntimeConfig {
    apiBase: string | number;
  }
}
// It is always important to ensure you import/export something when augmenting a type
export {};
```

[Commit 2 - Manually typing works fine and types from 'index.d.ts' are infered as expected](https://github.com/divagueame/runtime-config-demo/commit/bcd56dc0c3fc4391cc1b57a3facaf44529115151)
![Image](https://github.com/user-attachments/assets/e4022476-c6ec-4855-b3d1-032913d15369)

[Commit 3 - Afer adding nuxt-security module, manual types are not working anymore ](https://github.com/divagueame/runtime-config-demo/commit/3f9780cd0d93a75d16e5f9054a6e07cebfd716b9)
![Image](https://github.com/user-attachments/assets/69c04b10-08aa-4c1c-a5e4-e3202426df86)

### Additional context

nuxt.config.ts
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2024-11-01",
  devtools: { enabled: true },

  runtimeConfig: {
    apiSecret: "", // can be overridden by NUXT_API_SECRET environment variable
    public: {
      apiBase: "", // can be overridden by NUXT_PUBLIC_API_BASE environment variable
    },
  },

  modules: ["nuxt-security"],
});
```

```
index.d.ts
declare module "nuxt/schema" {
  interface RuntimeConfig {
    apiSecret: string;
  }
  interface PublicRuntimeConfig {
    apiBase: string | number;
  }
}
// It is always important to ensure you import/export something when augmenting a type
export {};
```

### Logs

```shell

```

**Comment by vejja** [comment]
Hi @divagueame 
Is the issue that the type of apiBase is `string` where it should be `string | number` ?

**Comment by divagueame** [comment]
> Hi [@divagueame](https://github.com/divagueame) Is the issue that the type of apiBase is `string` where it should be `string | number` ?

Correct.

Another example, here it should be the union:
  interface PublicRuntimeConfig {
    apiBase: "meow" | "woof";
  }


![Image](https://github.com/user-attachments/assets/37670c4a-df6b-4e84-b806-bf17b21621dd)

When i add nuxt security module:
![Image](https://github.com/user-attachments/assets/07fdab82-2c7b-4e2f-ac52-d927e5589c65)

**Comment by vejja** [comment]
Hi @divagueame 

I'm using your Github repro and I don't understand where Nuxt Security is involved.

I can see the types being overwritten, that's right. But on my end the behavior is exactly the same whether or not Nuxt Security is installed.
Can you elaborate a bit more and explain which setup I need to have in order to explicitly demonstrate that the issue is linked to Nuxt Security ?
Thanks

**Comment by divagueame** [comment]
@vejja Thanks for taking a look into this.

I think you can see the issue if you check my repo on the second commit:

```
git clone https://github.com/divagueame/runtime-config-demo.git
cd runtime-config-demo
git checkout bcd56dc0c3fc4391cc1b57a3facaf44529115151
npm install
```

Go to plugins/config.ts and check if the type is a union (it should be). Here on my side:
![Image](https://github.com/user-attachments/assets/4bd4ff8f-c86e-4edc-81d9-411ab89a5f3e)

Then run 

`npx nuxi@latest module add security`

and check again plugins/config.ts, now, on my side,  now it's just typed as string, but I expected it still to be a union (string | number).
![Image](https://github.com/user-attachments/assets/7c4ca35f-bb63-4b6d-8af9-7b74c7ba5bed)

Maybe it's the issue does not stem on nuxt security itself, that I don't know but it seems to occur when I add it. I had a similar issue on a bigger project and removing nuxt security was the toggle point for me.
Let me know if I can help in any other way.

**Comment by vejja** [comment]
The type is a string on my end

![Image](https://github.com/user-attachments/assets/22802505-4cee-4e72-8033-614df9689679)

I'm in a standard Github Codespace, editing with VSCode

**Comment by divagueame** [comment]
I tested on vscode on my side and I get the same behaviour. On this gif you can see the steps I commented above.

`npm install`

Then I check the type of `config.public.apiBase` and it's _string | number_ as expected.

`npx nuxi@latest module add security`


Then I check the type of `config.public.apiBase` and it's unkown.
Then I close and open vscode and it's _string_. Which is not what is expected, it should still be _string | number_

![Image](https://github.com/user-attachments/assets/9b74b870-74db-43eb-86c4-252fd70a7418)

is it a string on your side at all moments?

**Comment by vejja** [comment]
@divagueame 
Edit.

My bad. After deleting `node_modules` and all build artefacts, I'm in line with you.
But now I have another deviation 😭

Let's try to find out if you have it also.

1- Without Nuxt Security
```
git checkout bcd56d
rm -rf node_modules
rm -rf .nuxt
npm install
```
Then `apiBase` has the right type:
![Image](https://github.com/user-attachments/assets/8e26c2a9-8758-4760-a8f1-6c4cb931554d)

2- With Nuxt Security
```
npx nuxi@latest module add security
```
Now `apiBase` is undefined
![Image](https://github.com/user-attachments/assets/a103df25-3ae0-4fb7-9998-a86c853cf813)

For sake of clarity: deleting node_modules and .nuxt, then npm reinstalling does not change the issue.

3- C-Surf Module interaction:

runtimeConfig().public has no properties except `csurf`:
![Image](https://github.com/user-attachments/assets/efe1406b-b38d-4565-bb80-d75ed6edf593)

The type definition of `PublicRuntimeConfig` is being forwarded to the `nuxt-csurf` module:
![Image](https://github.com/user-attachments/assets/e3b7a749-faa5-46a7-838f-2cd11239779a)


Do you have the same analysis on your side ?

**Comment by vejja** [comment]
@divagueame 

I don't think this is related to Nuxt Security.

If you do what you described above (close and reopen VSCode) without installing Nuxt Security, the types are also destroyed

**Comment by divagueame** [comment]
> [@divagueame](https://github.com/divagueame)
> 
> I don't think this is related to Nuxt Security.
> 
> If you do what you described above (close and reopen VSCode) without installing Nuxt Security, the types are also destroyed

I agree with your assessment. It seems this happens independently from Nuxt Security. I'll try to open to an issue on Nuxt repository. Thanks a lot for your help.

**Comment by vejja** [comment]
Thanks @divagueame 
I think it is probably related to the way `nuxi prepare` generates the dynamic types, but I could be wrong.
Will close here
